config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  get 'privacy-policy' => 'pages#privacy_policy'
  get 'contact' => 'pages#contact'
  get 'about' => 'pages#about'
  get 'term' => 'pages#term'
  get 'sitemap' => 'pages#sitemap'
  get 'component-library' => 'pages#component_library' if Rails.env.development?

  get 'login' => 'sessions#new'
  resources :sessions, only: %i[create]
  get 'logout' => 'sessions#destroy'

  get 'signup' => 'users#new'
  resources :users, only: %i[create]
  resources :relay_mangas, only: %i[index show update], path: '/relay-magnas'

  namespace :internal do
    namespace :api do
    end
  end

  namespace :admin do
  end

  get '/404' => 'errors#render_404'
  get '/500' => 'errors#render_500'

  get 'sys/health_check' => Proc.new { [200, {'Content-Type' => 'text/plain'}, ['healty']] }

  get '*path', controller: 'application', action: 'render_404'

end

app/models/relay_manga.rb
require 'csv'

class RelayManga < ApplicationRecord
  has_many :relay_manga_genres
  has_many :genres, through: :relay_manga_genres
  has_many :manga_frames

  enum status: {
    draft: 1,
    released: 2,
  }, _prefix: true

  # csv_path = Rails.root.join('lib/assets/relay_manga_list.csv')
  def self.import_from_csv(csv_path)
    csv = CSV.table(csv_path)[1..-1].map(&:to_hash).map(&:with_indifferent_access)
    csv.select { |c| c.except('id').values.all?(&:present?) }.each do |row|
      relay_manga = self.find_or_initialize_by(id: row[:id]) do |manga|
        manga.title = row[:title]
      end
      relay_manga.relay_manga_genres.destroy_all
      genre1 = Genre.find_or_initialize_by(name: row[:genre1])
      genre2 = Genre.find_or_initialize_by(name: row[:genre2])
      [genre1, genre2].each do |genre|
        relay_manga.genres << genre
      end
      relay_manga.save!
    end
  end
end

app/controllers/relay_mangas_controller.rb
class RelayMangasController < ApplicationController
  def index
    @relay_mangas = RelayManga.all.order('genres.id asc').includes(:genres).decorate
  end

  def show
    @relay_manga = RelayManga.find_by(id: params[:id])
  end

  def update
    return redirect_to root_path unless current_user

    @relay_manga = RelayManga.find_by(id: params[:id])
    MangaFrame.create(
      { user: current_user, relay_manga: @relay_manga }.merge(manga_frame_params)
    )

    redirect_to action: :show
  end

  private

  def manga_frame_params
    params.require(:manga_frame).permit(:meta)
  end
end

app/views/relay_mangas/index.html.slim
.l-main-content

  .breadcrumb.l-mb-xs-15.l-mb-sm-30
    ol
      li = link_to 'ホーム', root_path
      li = 'リレー漫画一覧'

  .l-container
    .l-row
      .l-col-md-12
        .l-mb-xs-10.l-mb-md-20
          h1.category-head__title = 'リレー漫画一覧'
        .l-col-md-12.l-mb-xs-15
          .link-list
            ul.link-list__list
              - @relay_mangas.each do |relay_manga|
                li
                  = link_to relay_manga.title_for_list, relay_manga_path(relay_manga)

app/views/relay_mangas/show.html.slim
.l-main-content

  .breadcrumb.l-mb-xs-15.l-mb-sm-30
    ol
      li = link_to 'ホーム', root_path
      li = link_to 'リレー漫画一覧', relay_mangas_path
      li = @relay_manga.title

  .l-container
    .l-row
      .l-col-md-12
        .category-head.l-mb-xs-10.l-mb-md-20
          h1.category-head__title = @relay_manga.title
          h1.category-head__genre = @relay_manga.genres.map(&:name).join('× ')
          p.category-head__description テキストテキスト
        - if current_user
          .l-col-md-12.l-mb-xs-15
            = form_with model: @relay_manga.manga_frames.new, url: relay_manga_path(@relay_manga), method: :put do |f|
              = f.file_field :meta
              = f.submit class: "waves-light btn mod-btn mod-btn--primary", data: { confirm: "ファイルをアップロードしますか？" }
        .l-col-md-12.l-mb-xs-15
          - @relay_manga.manga_frames.includes(:user).order('manga_frames.id asc').select(&:persisted?).each do |frame|
            .l-col-sm-6.l-col-lg-4.l-mb-xs-10.l-mb-lg-20.relay-manga--show__frame[style="margin: auto;"]
              = "投稿者：#{frame.user.nickname}"
              br
              img[src="#{frame.meta_url}" style="width: 80%;"]